### ISSUE TITLE
Dockerize App

### ISSUE THREAD

**Issue by gambinish** [melsoriano/share-tunes#8]
-Docker-Compose
-Express Server
-React

**Comment by gambinish** [comment]
Decision was made alter the docker-compose file to dockerize the express server, and run it on ec2 while automating the front end static deployment build to s3

**Comment by gambinish** [comment]
Keeping separate Dockerfile and package.json files for now. Refactoring to point to single package.json seems over-complex for early on in the project

**Comment by gambinish** [comment]
Issue with remote gprc library (likely from firebase-admin) can't install from within docker container.

Solution is to remove dependency from server directory, uncomment:
`const utils = require('./utils/_firebaseUtils');`

docker-compose up --build

docker exec -it <container id> bash

npm install firebase firebase-admin

apt-get update
apt-get install vim

docker-compose down

docker-compose up

server runs without errors

**Comment by melsoriano** [comment]
Fixed in PR #18
